### ISSUE TITLE
Documentar código

### ISSUE THREAD

**Issue by paulojunior-ufla** [ufla-gcc259/aula-git-parte-2#45]
Escrever comentários no código, documentando as **funções** e **constantes** públicas da biblioteca.

**Comment by pauloafpjunior** [comment]
Há alguém trabalhando nesta issue? Caso contrário, eu poderia resolvê-la.

**Comment by paulojunior-ufla** [comment]
@pauloafpjunior fique à vontade. Aguardo seu PR...
